export const listProduct = [
    {
      name: "Điện Thoại Vsmart Joy 3 - Hàng chính hãng",
      price: "1.790.000",
      color: "Xanh",
      background : "#234896",
      colorName : "blue",
      rating: 5,
      ratingCount: 182,
      image: require("./assets/vs_blue.png"),
    },
    {
      name: "Điện Thoại Vsmart Joy 3 - Hàng chính hãng",
      price: "1.790.000",
      color: "Đen",
      background : "#000000",
      colorName : "black",
      rating: 5,
      ratingCount: 182,
      image: require("./assets/vs_black.png"),
    },
    {
      name: "Điện Thoại Vsmart Joy 3 - Hàng chính hãng",
      price: "1.790.000",
      color: "Bạc",
      background : "#C5F1FB",
      colorName : "siliver",
      rating: 5,
      ratingCount: 182,
      image: require("./assets/vs_siliver.png"),
    },
    {
      name: "Điện Thoại Vsmart Joy 3 - Hàng chính hãng",
      price: "1.790.000",
      color: "Đỏ",
      background : "#F30D0D",
      colorName : "red",
      rating: 5,
      ratingCount: 182,
      image: require("./assets/vs_red.png"),
    },
  ];